version: "3.5"

services:
  phpslim:
    build: ./php
    volumes:
      - ./app-php:/usr/src/app
    expose:
      - 80
    links:
      - db
    restart:
      on-failure
    networks:
      appnet:
        ipv4_address: "172.254.0.3"
  
  web:
    image: "nginx:1.13.8-alpine"
    volumes:
      #- ./app:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    links:
      - phpslim
    restart:
      on-failure
    networks:
      appnet:
        ipv4_address: "172.254.0.2"

  db:
    image: mysql:5.7
    env_file:
      - ./mysql/.env
    volumes:
      - ./mysql/.data:/var/lib/mysql
    expose:
      - 3306
    restart:
      on-failure
    networks:
      appnet:
        ipv4_address: "172.254.0.4"

networks:
  appnet:
    name: php-app
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 172.254.0.0/24