<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <title>Gestão Empresarial</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    </head>
    <body>
    <div class="container">
            <div class="row">
        <center><h2>Lista de Usuários</h2></center>
        <h3><p> Realizar <a href="/api/logout">Logout</a></h3>
            <table class="table table-hover">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">Registro</th>
                    <th scope="col">Nome</th>
                    <th scope="col">CPF</th>
                    <th scope="col">Email</th>
                </tr>
            </thead>
            <tbody>
            <?php if(!empty($users)) : ?>
            <?php foreach ($users as $user): ?>
                <tr>
                    <td scope="row"><?= $user->user_id ?></td>
                    <td><?= $user->nome ?></td>
                    <td><?= $user->cpf ?></td>
                    <td><?= $user->email ?></td>
                    <td><a href="/api/user/<?= $user->user_id ?>"><button type="button" class="btn btn-info btn-sm">Detalhes</button></a></td>
                    <td><a href="/api/user/update/<?= $user->user_id ?>"><button type="button" class="btn btn-primary btn-sm">Atualizar</button></a></td>
                </tr>
            <?php endforeach; ?>
            <?php endif; ?>
        </div>
        </div>
    </body>
</html>