<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <title>Gestão Empresarial</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-md-9">
                    <div class="text-center">
                        <h2>Registro</h2>
                    </div>
                    <form action="/api/registry" method="POST">
                        <table class="table">
                            <thead>
                                <tr>
                                <th></th>
                                <th></th>
                                </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <th>
                                    <td align="right">
                                        <label for="nome">Nome</label>
                                    </td>
                                    <td>    
                                        <input type="text" class="form-control" id="nome" name="nome" aria-describedby="nome" placeholder="nome" required>
                                    </td>
                                </th>
                            </tr>
                            <tr>
                                <th>
                                    <td align="right">
                                        <label for="cpf">CPF</label>
                                    </td>
                                    <td>    
                                        <input type="text" class="form-control" id="cpf" name="cpf" aria-describedby="cpf" placeholder="cpf" required>
                                    </td>
                                </th>
                            </tr>
                            <tr>
                            <th >
                            <td align="right">
                                    <label for="telefone">Telefone</label>
                                    </td>
                                    <td>    
                                    <input type="text" class="form-control" id="telefone" name="telefone" aria-describedby="telefone" placeholder="telefone" required>
                                    </td>
                                </th>
                            </tr>
                            <tr>
                                <th>
                                    <td align="right">
                                        <label for="email">Email</label>
                                    </td>
                                    <td>    
                                        <input type="text" class="form-control" id="email" name="email" aria-describedby="email" placeholder="email" required>
                                    </td>
                                </th>
                            </tr>
                            <tr>
                                <th >
                                    <td align="right">
                                        <label for="data_nascimento">Data Nascimento</label>
                                    </td>
                                    <td>    
                                    <input type="date" class="form-control" width="" id="data_nascimento" name="data_nascimento" aria-describedby="data_nascimento" placeholder="data_nascimento" required>
                                    </td>
                                </th>
                            </tr>
                            <tr>
                                <th >
                                    <td align="right">
                                        <label for="rua">Rua</label>
                                    </td>
                                    <td>    
                                    <input type="text" class="form-control" id="rua" name="rua" aria-describedby="rua" placeholder="rua" required>
                                    </td>
                                </th>
                            </tr>
                            <tr>
                                <th >
                                    <td align="right">
                                        <label for="numero">Número</label>
                                    </td>
                                    <td>    
                                    <input type="number" class="form-control" min="0" max="99999" id="numero" name="numero" aria-describedby="numero" placeholder="numero" required>
                                    </td>
                                </th>
                            </tr>
                            <tr>
                                <th >
                                    <td align="right">
                                        <label for="bairro">Bairro</label>
                                    </td>
                                    <td>    
                                    <input type="text" class="form-control" id="bairro" name="bairro" aria-describedby="bairro" placeholder="bairro" required>
                                    </td>
                                </th>
                            </tr>
                            <tr>
                                <th >
                                    <td align="right">
                                        <label for="cidade">Cidade</label>
                                    </td>
                                    <td>    
                                        <input type="text" class="form-control" id="cidade" name="cidade" aria-describedby="cidade" placeholder="cidade" required>
                                    </td>
                                </th>
                            </tr>
                            <tr>
                                <th >
                                    <td align="right">
                                        <label>Estado:</label>
                                    </td>
                                    <td>    
                                        <input type="text" class="form-control" id="estado" name="estado" aria-describedby="estado" placeholder="estado" required>
                                    </td>
                                </th>
                            </tr>
                            <tr>
                                <th >
                                    <td align="right">
                                        <label for="complemento">Complemento</label>
                                    </td>
                                    <td>    
                                        <input type="text" class="form-control" id="complemento" name="complemento" aria-describedby="complemento" placeholder="complemento">
                                    </td>
                                </th>
                            </tr>
                            <tr>
                                <th >
                                  
                                    <td align="right">
                                        <label for="senha">Senha</label>
                                    </td>
                                    <td> 
                                        <input type="password" class="form-control" id="senha" name="senha" aria-describedby="senha" placeholder="senha" minlength="8" required>
                                    </td>
                                </th>
                            </tr>
                            <tr>
                                <th >
                                    <td align="right">
                                    </td>
                                    <td>    
                                    <input type="submit" value="Registrar" class="btn btn-primary"/>
                                    </td>
                                </th>
                            </tr>
                            </tbody>
                        </table> 
                    </form>
                </div>
            </div>
        </div>
    </body>
</html>